import os
import datetime as dt
from typing import Optional, List

import pandas as pd


def get_project_dir() -> str:
    return os.path.dirname(os.path.abspath(__file__))


def read_csv_if_exists(path: str) -> Optional[pd.DataFrame]:
    if os.path.exists(path):
        try:
            return pd.read_csv(path)
        except Exception:
            return None
    return None


def safe_to_html(df: Optional[pd.DataFrame], max_rows: int = 200) -> str:
    if df is None or df.empty:
        return '<p><em>无可用数据</em></p>'
    df_show = df.copy()
    if len(df_show) > max_rows:
        df_show = df_show.head(max_rows)
    return df_show.to_html(index=False, escape=False, border=0, classes=['data-table'])


def list_existing_images(dir_path: str, patterns: List[str]) -> List[str]:
    if not os.path.isdir(dir_path):
        return []
    files = []
    for name in sorted(os.listdir(dir_path)):
        lower = name.lower()
        if any(p.lower() in lower for p in patterns):
            files.append(os.path.join(dir_path, name))
    return files


def build_html() -> str:
    base_dir = get_project_dir()
    inter_dir = os.path.join(base_dir, 'intermediate')
    plots_dir = os.path.join(base_dir, 'consistency_plots')

    # Load tables (reuse if already generated by previous scripts) - V2版本
    desc_csv = os.path.join(inter_dir, 'summary_descriptives_v2.csv')
    icc_csv = os.path.join(inter_dir, 'icc_results_v2.csv')
    within_csv = os.path.join(inter_dir, 'within_group_tests_v2.csv')

    df_desc = read_csv_if_exists(desc_csv)
    df_icc = read_csv_if_exists(icc_csv)
    df_within = read_csv_if_exists(within_csv)

    # Images - V2版本
    icc_summary_img = os.path.join(plots_dir, 'icc_by_condition_summary_scores_v2.png')
    paired_imgs = list_existing_images(plots_dir, patterns=['paired_lines_', '_v2.png'])
    diff_bar_imgs = list_existing_images(plots_dir, patterns=['diff_bar_', '_v2.png'])
    diff_box_imgs = list_existing_images(plots_dir, patterns=['diff_box_', '_v2.png'])

    # Basic inline CSS
    style = '''
    <style>
    body { font-family: -apple-system, BlinkMacSystemFont, Segoe UI, Roboto, Helvetica, Arial, \"Noto Sans\", \"Apple Color Emoji\", \"Segoe UI Emoji\"; margin: 24px; }
    h1, h2, h3 { margin: 0.4em 0 0.2em; }
    .meta { color: #666; font-size: 0.9em; margin-bottom: 18px; }
    .section { margin: 26px 0; }
    .data-table { border-collapse: collapse; width: 100%; font-size: 14px; }
    .data-table th, .data-table td { border: 1px solid #e5e7eb; padding: 6px 8px; }
    .data-table th { background: #f8fafc; text-align: left; }
    .hint { color: #374151; background: #f3f4f6; padding: 10px 12px; border-radius: 6px; }
    img.figure { max-width: 100%; height: auto; border: 1px solid #e5e7eb; border-radius: 6px; margin: 8px 0; }
    .grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(280px, 1fr)); gap: 12px; }
    </style>
    '''

    # Sections
    now = dt.datetime.now().strftime('%Y-%m-%d %H:%M')
    html = [
        '<!DOCTYPE html>',
        '<html lang="zh-CN">',
        '<head>',
        '<meta charset="utf-8"/>',
        '<meta name="viewport" content="width=device-width, initial-scale=1"/>',
        f'<title>专家评分分析报告 - V2版本</title>',
        style,
        '</head>',
        '<body>',
        '<h1>专家评分分析报告 - V2版本</h1>',
        f'<div class="meta">生成时间：{now}</div>',
        '<div class="meta"><strong>注意：</strong>本报告为V2版本，排除了O7、O8列、Outcome Score和Total Score，只分析Process Score</div>',

        '<div class="section">',
        '<h2>1. 描述性统计</h2>',
        '<div class="hint">说明：本表给出两位专家（E1/E2）在Process Score上的分布特征，包括均值、标准差及分位数；同时提供按条件（AI/NoAI）分组的统计。用于观察分布是否存在天花板/地板效应与条件差异。若表格为空，请先运行前置脚本生成中间结果：expert_consistency_analyzer_v2.py、within_group_analysis_v2.py。</div>',
        safe_to_html(df_desc),
        '</div>',

        '<div class="section">',
        '<h2>2. 专家间一致性（ICC）</h2>',
        '<div class="hint">说明：ICC(2,k) 为双向随机效应、绝对一致、平均评分。一致性阈值常用：≥0.70 可合并；0.50–0.70 中等一致性（谨慎解读）；<0.50 不建议合并。表中CI为95%置信区间，若跨0则一致性证据不足。Overall 使用全部样本；Condition=AI/NoAI 分别仅使用对应条件的样本。V2版本只分析Process Score。</div>',
        safe_to_html(df_icc),
    ]

    if os.path.exists(icc_summary_img):
        rel = os.path.relpath(icc_summary_img, base_dir)
        html += [f'<img class="figure" src="{rel}" alt="ICC by Condition (Summary Scores) - V2"/>']

    html += ['</div>']

    html += [
        '<div class="section">',
        '<h2>3. 组内对照（AI vs NoAI）</h2>',
        '<div class="hint">说明：本部分展示每个组在AI和NoAI条件下的差异分析。V2版本只分析Process Score，排除了Outcome Score和Total Score。</div>',
        safe_to_html(df_within),
    ]

    # 3.1 配对连线图
    if paired_imgs:
        html += [
            '<h3>3.1 配对连线图（每组从 NoAI 到 AI 的变化）</h3>',
            '<div class="hint">说明：每条线代表一个组，从 NoAI 指向 AI。可直观看到各组方向与幅度；若线条方向杂乱，说明不同组变化趋势不一致。V2版本只显示Process Score的分析结果。</div>',
            '<div class="grid">'
        ]
        for img in paired_imgs:
            rel = os.path.relpath(img, base_dir)
            alt = os.path.basename(img)
            html += [f'<div><img class="figure" src="{rel}" alt="{alt}"/><div style="font-size:12px;color:#6b7280;">{alt}</div></div>']
        html += ['</div>']

    # 3.2 差值柱状图
    if diff_bar_imgs:
        html += [
            '<h3>3.2 差值柱状图（AI − NoAI）</h3>',
            '<div class="hint">说明：每根柱表示一个组的差值（AI−NoAI），上方红线为整体均值，虚线为95%CI。整体均值与零线的关系体现总体差异方向与大小。V2版本只显示Process Score的分析结果。</div>',
            '<div class="grid">'
        ]
        for img in diff_bar_imgs:
            rel = os.path.relpath(img, base_dir)
            alt = os.path.basename(img)
            html += [f'<div><img class="figure" src="{rel}" alt="{alt}"/><div style="font-size:12px;color:#6b7280;">{alt}</div></div>']
        html += ['</div>']

    # 3.3 差值箱线图
    if diff_box_imgs:
        html += [
            '<h3>3.3 差值箱线图（AI − NoAI 的分布）</h3>',
            '<div class="hint">说明：展示所有组的差值分布与离群点，红线为均值。与柱状图互为补充，有助于识别分布偏态与极端值。V2版本只显示Process Score的分析结果。</div>',
            '<div class="grid">'
        ]
        for img in diff_box_imgs:
            rel = os.path.relpath(img, base_dir)
            alt = os.path.basename(img)
            html += [f'<div><img class="figure" src="{rel}" alt="{alt}"/><div style="font-size:12px;color:#6b7280;">{alt}</div></div>']
        html += ['</div>']

    html += ['</div>']

    html += [
        '<div class="section">',
        '<h2>4. 解读提示</h2>',
        '<ul>',
        '<li>ICC ≥ 0.70：可合并；0.50–0.70：中等一致性，谨慎解读；&lt; 0.50：不建议合并。</li>',
        '<li><strong>V2版本说明：</strong>本版本排除了O7、O8列、Outcome Score和Total Score，只分析Process Score。</li>',
        '<li>组内对照建议优先 Wilcoxon；同时报告效应量与多重比较校正结果。</li>',
        '<li>若需要查看包含Outcome Score的完整分析，请参考原版本报告。</li>',
        '</ul>',
        '</div>',

        '</body>',
        '</html>'
    ]

    return '\n'.join(html)


def main() -> None:
    base_dir = get_project_dir()
    out_path = os.path.join(base_dir, 'expert_scoring_report_v2.html')
    os.makedirs(base_dir, exist_ok=True)

    html = build_html()
    with open(out_path, 'w', encoding='utf-8') as f:
        f.write(html)

    print(f"V2版本报告已生成: {out_path}")
    print("注意：本报告排除了O7、O8列、Outcome Score和Total Score，只分析Process Score")


if __name__ == "__main__":
    main()
